//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentNote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operational
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Operational()
        {
            this.OperationalDetails = new HashSet<OperationalDetail>();
        }
    
        public string po_id { get; set; }
        public string company_code { get; set; }
        public string currency { get; set; }
        public Nullable<long> currency_rate { get; set; }
        public string status { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> edited_at { get; set; }
        public string edited_by { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public string deleted_by { get; set; }
        public Nullable<int> vendor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationalDetail> OperationalDetails { get; set; }
        public virtual Vendor Vendor1 { get; set; }
    }
}
