//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentNote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Backup
    {
        public int user_id { get; set; }
        public string username { get; set; }
        public string first_name { get; set; }
        public string password { get; set; }
        public string location { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string edited_by { get; set; }
        public Nullable<System.DateTime> edited_at { get; set; }
        public string deleted_by { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<bool> is_admin { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> Last_Login { get; set; }
    }
}
